config/routes.rb
Rails.application.routes.draw do
  root 'sales#index'
  get 'sales' => 'sales#index'
  post 'shops/:shop_id/sales/' => 'sales#update'
  resources :products do 
    resources :sales
  end
  resources :shops do
    resources :sales
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :sales
  has_many :shops, through: :sales
end

app/models/sale.rb
class Sale < ApplicationRecord
  belongs_to :shop
  belongs_to :product
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :sales
  has_many :products, through: :sales

  accepts_nested_attributes_for :sales, allow_destroy: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :show]

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.create(product_params)
    if @product.save
      @product.sales.create(price: 0)
      Shop.all.each do |shop|
        shop.products << @product
      end
      redirect_to @product
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @product.update(product_params)
      redirect_to @product
    else
      render :edit
    end
  end

  def show
  end



  private
  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name)
  end

end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  REGISTRABLE_ATTRIBUTES = %i(id shop_id product_id price)

  def index
    @sales = Sale.order(:shop_id, :product_id)
  end

  # def new
  #   @sales = Product.sales.new
  # end

  # def create
  # end

  def update
    sale_params[:sales_attributes].each do |sale|
      Sale.find(sale[1].to_hash["id"]).update(sale[1])
    end
  end

  private
  def sale_params
    params.require(:shop).permit(:id, [sales_attributes: REGISTRABLE_ATTRIBUTES])
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:edit, :update, :show]

  def index
    @shops = Shop.all
  end

  def new
    @shop = Shop.new
  end

  def create
    @shop = Shop.create(shop_params)
    if @shop.save
      @shop.sales.create(price: 0)
      Product.all.each do |product|
        product.shops << @shop
      end
      redirect_to @shop
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @shop.update(shop_params)
      redirect_to @shop
    else
      render :edit
    end
  end

  def show
  end



  private
  def set_shop
    @shop = Shop.find(params[:id])
  end

  def shop_params
    params.require(:shop).permit(:name, :store_name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoRSample02</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container">
      <div>
        <p><%= link_to '店情報', shops_path %></p>
        <p><%= link_to '商品情報', products_path %></p>
        <p><%= link_to '販売情報', sales_path %></p>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_with model: @product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.submit %>
<% end %>

app/views/products/edit.html.erb
<h2>編集</h2>
<%= render 'form' %>

app/views/products/index.html.erb
<table class="table">
<thead>
<tr>
<th>商品名</th>
</tr>
</thead>
<tbody>
<% @products.each do |product| %>
<tr>
<td><%= product.name %></td>
<td><%= link_to '編集', edit_product_path(product) %>
</tr>
<% end %>
</tbody>
</table>
<%= link_to '商品追加', new_product_path %>

app/views/products/new.html.erb
<h2>新規</h2>
<%= render 'form' %>

app/views/products/show.html.erb
<%= @product.name %>
<%= link_to '戻る', products_path %>

app/views/sales/_form.html.erb
<tr>
<%= f.hidden_field :shop_id %>
<%= f.hidden_field :product_id %>
<%= f.hidden_field :id %>
<td><%= f.object.product.name %></td>
<td><%= f.text_field :price %></td>
</tr>

app/views/sales/index.html.erb
<table class="table">
<thead>
<tr>
<th>店名</th>
<th>店舗名</th>
<th>商品名</th>
<th>価格</th>
</tr>
</thead>
<tbody>
<% @sales.each do |sale| %>
<tr>
<td><%= sale.shop.name %></td>
<td><%= sale.shop.store_name %></td>
<td><%= sale.product.name %></td>
<td><%= sale.price%></td>
</tr>
<% end %>
</tbody>
</table>

app/views/shops/_form.html.erb
<%= form_with model: @shop do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<%= f.label :store_name %>
<%= f.text_field :store_name %>
<%= f.submit %>
<% end %>

app/views/shops/edit.html.erb
<h2>編集</h2>
<%= render 'form' %>

app/views/shops/index.html.erb
<table class="table">
<thead>
<tr>
<th>店名</th>
<th>店舗名</th>
</tr>
</thead>
<tbody>
<% @shops.each do |shop| %>
<tr>
<td><%= shop.name %></td>
<td><%= shop.store_name %></td>
<td><%= link_to '編集', edit_shop_path(shop) %>
<td><%= link_to '詳細', shop_path(shop) %>
</tr>
<% end %>
</tbody>
</table>
<%= link_to '店追加', new_shop_path %>

app/views/shops/new.html.erb
<h2>新規</h2>
<%= render 'form' %>

app/views/shops/show.html.erb
<div>
<%= @shop.name %>
<%= @shop.store_name %>
</div>
<%= link_to '戻る', shops_path %>
<%= form_with model: @shop, url: "/shops/#{@shop.id}/sales", method: 'POST' do |f| %>
<%= f.hidden_field :id %>
<table>
<thead>
<tr>
<th>商品名</th>
<th>価格</th>
</tr>
</thead>
<tbody>
<%= f.fields_for :sales do |sale| %>
<%= render 'sales/form', f: sale %>
<% end %>
</tbody>
</table>
<%= f.submit %>
<% end %>